import type { PageSection } from '../shared/settings'
import { SECTION_TARGETS } from './selectors'

/**
 * Set on `<html>` once the content script has read settings and applied them.
 * Its absence means "not decided yet", never "nothing is blocked", which is why
 * teardown sets it rather than clearing it: an unloaded extension must not
 * leave the page hidden.
 */
export const READY_ATTR = 'data-ltfb-ready'

/**
 * The sections the stylesheet can cover. Three of the five cannot be expressed
 * in CSS at all: `networkPuzzle` and `networkPremium` match on text content,
 * and `networkSuggestions` compares document position against the pending
 * invitations preview. They keep the JavaScript path and are unaffected by any
 * of this.
 *
 * The split falls on the route boundary, which is what makes a partial
 * migration worth doing: `/feed/` is entirely CSS-expressible and `/feed/` is
 * where the flash actually hurts.
 */
export const CURTAIN_SECTIONS: PageSection[] = ['feed', 'rightFeed']

/**
 * How long the stylesheet hides its targets when nothing ever clears the gate.
 * The content script normally clears it in milliseconds; this is the backstop
 * for the case where the content script's JavaScript never runs at all, which
 * would otherwise leave LinkedIn permanently blank.
 *
 * `display: none` cannot be lifted by an animation in either engine, which is
 * why the curtain is `content-visibility` plus `visibility` instead. Verified
 * against Chromium and Firefox before this was written: `content-visibility`
 * collapses a container's box the way `display: none` does but does not hide a
 * replaced element, and `visibility` hides the ad image and iframe but reserves
 * their space. Together they cover both, and both properties can be animated
 * back, which `display` cannot.
 */
export const CURTAIN_EXPIRY_MS = 4000

/**
 * The content script's own backstop, well under the stylesheet's, so the
 * ordinary recovery from a storage read that never returns is a JavaScript one
 * and the CSS expiry stays the last resort.
 */
export const READY_FALLBACK_MS = 1500

const LIFT_ANIMATION = 'ltfb-curtain-lift'

/**
 * The selectors the curtain hides. Read out of `SECTION_TARGETS` rather than
 * restated, so the stylesheet and the JavaScript path cannot drift apart: a
 * selector edit that only lands in one of them is not possible.
 */
export const getCurtainSelectors = () => {
  return CURTAIN_SECTIONS.flatMap(section =>
    SECTION_TARGETS[section].map(target => {
      if (typeof target !== 'string') {
        // A predicate-gated target cannot be expressed in CSS. Failing here
        // fails the generator, which fails the checked-in file's guard, rather
        // than silently emitting a rule that hides more than the JS would.
        throw new Error(
          `${section} has a predicate-gated target and cannot be in ` +
            'CURTAIN_SECTIONS',
        )
      }

      return target
    }),
  )
}

export const buildBlockingCss = () => {
  const selectors = getCurtainSelectors()
    .map(selector => `html:not([${READY_ATTR}]) ${selector}`)
    .join(',\n')

  return `/*
 * Generated by src/content/blockingStyles.ts. Do not edit.
 * Run UPDATE_BLOCKING_CSS=1 pnpm test to regenerate.
 *
 * Declared at document_start so the sections below are hidden before the first
 * paint, rather than after the content script's first pass. It hides the union
 * of the feed route's targets, because nothing knows which sections are blocked
 * until the settings read lands; a section the user left unblocked therefore
 * appears a moment after load rather than being hidden a moment after it.
 *
 * The animation is a backstop, not decoration. If the content script never runs
 * the gate never clears, and without it LinkedIn would stay blank.
 */

@keyframes ${LIFT_ANIMATION} {
  to {
    content-visibility: visible;
    visibility: visible;
  }
}

${selectors} {
  content-visibility: hidden;
  visibility: hidden;
  animation: 0s linear ${CURTAIN_EXPIRY_MS}ms forwards ${LIFT_ANIMATION};
}
`
}

/**
 * One-way on purpose: see `READY_ATTR`.
 */
export const markBlockingReady = () => {
  document.documentElement.setAttribute(READY_ATTR, 'true')
}

export const isBlockingReady = () => {
  return document.documentElement.hasAttribute(READY_ATTR)
}
